run:
    cargo run

# run build when sources change (requires https://github.com/watchexec/watchexec)
watch:
    # Watch all rs and toml files in the current directory and all
    # subdirectories for changes.  If something changed, re-run the build.
    @watchexec -r --clear --exts rs,toml -- just run

build: lint
    cargo build

lint:
    # Default clippy settings (used by `cargo [build, test]` automatically):
    #
    #   cargo clippy
    #
    # If you want stricter clippy settings, start with the suggestion below
    # and consider adding this `lint` target as a dependency to other just
    # targets like `build` and `test`.
    #
    # --all-targets:  check sources and tests
    # --all-features: check non-default crate features
    # -D warnings:    fail the build when encountering warnings
    #
    cargo clippy --verbose --all-targets --all-features -- -D warnings

# run tests (requires https://nexte.st/)
test: lint
    cargo nextest run

# run tests in vanilla mode (use when nextest is not installed)
test-vanilla: lint
    cargo test


# run check then tests when sources change (requires https://github.com/watchexec/cargo-watch)
watch-test:
    cargo watch -q -c -x check -x 'nextest run'

